# Use the official Python 3.8 image as the base image
FROM python:3.13

# Install nano
RUN apt-get update && \
    apt-get install -y nano --no-install-recommends && \
    rm -rf /var/lib/apt/lists/*
# Set the working directory in the container
WORKDIR /code/app

# Copy the requirements file to the working directory
COPY requirements.txt .

# Install the dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the application code to the working directory
COPY ./backend .

# # Expose the port FastAPI will run on
# EXPOSE 8000

# Command to run the FastAPI server
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8007", "--reload"]